In [7]:
import numpy as np
x = np.array([1,2,3], dtype=np.float64)
x 

array([ 1.,  2.,  3.])

In [8]:
x.itemsize

8

In [10]:
# ex: the benefit of using numpy
np.sin(np.array([1,2,3],dtype=np.float64))

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [11]:
# otherwise:
from math import sin
[sin(i) for i in [1,2,3]]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [12]:
# 2-D array
x = np.array([[1,2,3],[4,5,6]])
x.shape 

(2, 3)

In [13]:
x[:,0] # 0th column

array([1, 4])

In [14]:
x[:,1] # 1st column

array([2, 5])

In [15]:
x[0,:] # 0th row

array([1, 2, 3])

In [16]:
x[:,1:] # all rows, 1st through last column

array([[2, 3],
       [5, 6]])

In [17]:
x[:,::2] # all rows, every other column

array([[1, 3],
       [4, 6]])

In [18]:
x[:,::-1] # reverse order of columns

array([[3, 2, 1],
       [6, 5, 4]])