In [2]:
import numpy as np
from matplotlib.pylab import subplots
from sklearn.linear_model import LinearRegression
X = np.arange(10) # create some data
Y = X+np.random.randn(10) # linear with noise

In [3]:
lr = LinearRegression() # create model

In [6]:
X,Y = X.reshape((-1,1)), Y.reshape((-1,1))
lr.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
lr.coef_

array([[ 0.99969864]])

In [8]:
lr.score(X,Y)

0.8633892779385739

In [10]:
xi = np.linspace(0,10,15) # more points to draw
xi = xi.reshape((-1,1)) # reshape as columns
yp = lr.predict(xi)

In [12]:
xi

array([[  0.        ],
       [  0.71428571],
       [  1.42857143],
       [  2.14285714],
       [  2.85714286],
       [  3.57142857],
       [  4.28571429],
       [  5.        ],
       [  5.71428571],
       [  6.42857143],
       [  7.14285714],
       [  7.85714286],
       [  8.57142857],
       [  9.28571429],
       [ 10.        ]])

In [13]:
yp

array([[  0.73750519],
       [  1.45157565],
       [  2.16564611],
       [  2.87971657],
       [  3.59378703],
       [  4.30785749],
       [  5.02192795],
       [  5.73599841],
       [  6.45006887],
       [  7.16413933],
       [  7.87820979],
       [  8.59228025],
       [  9.30635071],
       [ 10.02042117],
       [ 10.73449163]])